### ISSUE TITLE
[Migration Tool] Create migration configuration system

### ISSUE THREAD

**Issue by medamap** [medamap/PoppoBuilderSuite#349]
## Overview
This issue implements a flexible configuration system for the migration tool, allowing users to customize migration behavior, rules, and output preferences.

## Parent Issue
Part of #333 - Migration Tool Development (Bash to Node.js)

## Objective
Build a configuration system that:
- Supports multiple configuration formats
- Provides sensible defaults
- Allows per-project customization
- Enables rule-based migrations

## Technical Requirements
1. **Configuration Format**
   - Support JSON, YAML, and JavaScript configs
   - Schema validation for configurations
   - Environment variable support
   - Configuration inheritance/merging

2. **Configuration Options**
   ```yaml
   # .migration-config.yaml
   version: 1.0
   migration:
     parser:
       strict: false
       bashVersion: 4.0
     generator:
       style: async-await
       typescript: false
       esmodules: true
     validation:
       skipTests: []
       customRules: []
     output:
       directory: ./migrated
       preserveStructure: true
   rules:
     - pattern: 'grep -E'
       template: 'regex-search'
     - pattern: 'find . -name'
       template: 'glob-search'
   ```

3. **Configuration Loading**
   - Cascading configuration (global → project → command-line)
   - Configuration validation and error reporting
   - Hot-reload support for development

## Acceptance Criteria
- [ ] Support for JSON, YAML, JS configuration files
- [ ] Schema validation prevents invalid configs
- [ ] Default configuration works out-of-the-box
- [ ] Per-project overrides are supported
- [ ] Environment variables can override settings
- [ ] Configuration documentation is comprehensive
- [ ] Migration rules are customizable
- [ ] Config generator CLI tool included

## Dependencies
- Depends on #343 (base architecture)

## Estimated Effort
- Development: 3 days
- Testing: 1 day
- Documentation: 1 day

## Configuration Features
1. **Parser Configuration**
   - Bash version compatibility
   - Strict mode vs permissive mode
   - Custom parser plugins

2. **Generator Configuration**
   - Code style preferences
   - Module system (CommonJS/ESM)
   - TypeScript output option
   - Template customization

3. **Validation Configuration**
   - Enable/disable specific checks
   - Custom validation rules
   - Warning vs error thresholds

4. **Migration Rules**
   - Pattern matching rules
   - Custom transformations
   - Command mappings
   - Library preferences

## CLI Integration
```bash
# Generate default config
poppo-migrate init

# Use custom config
poppo-migrate --config custom.yaml

# Override specific options
poppo-migrate --generator.typescript=true

# Validate configuration
poppo-migrate validate-config
```

## Additional Notes
- Include configuration migration tool
- Support for plugins via config
- Preset configurations for common scenarios
- Integration with PoppoBuilder config system
