### ISSUE TITLE
[#337-6] Add support for label templates

### ISSUE THREAD

**Issue by medamap** [medamap/PoppoBuilderSuite#390]
## Overview
Implement a template system for generating labels with variables and patterns.

## Parent Issue
- #337: Quick Win: create-github-labels.sh Migration

## Dependencies
- Requires #386 (Configuration system) completion

### 1. Template Parsing Tests
```javascript
// Test template variable extraction
test('should extract variables from template', () => {
  const template = 'task:${type}';
  const vars = extractVariables(template);
  expect(vars).toEqual(['type']);
});

test('should handle multiple variables', () => {
  const template = '${category}:${name}-${variant}';
  const vars = extractVariables(template);
  expect(vars).toEqual(['category', 'name', 'variant']);
});

test('should reject invalid template syntax', () => {
  expect(() => parseTemplate('task:${}')).toThrow('Invalid template syntax');
  expect(() => parseTemplate('${unclosed')).toThrow('Unclosed variable');
});
```

### 2. Template Expansion Tests
```javascript
test('should expand template with values', () => {
  const template = {
    name: 'task:${type}',
    description: '${type} task',
    color: '${color}'
  };
  
  const expanded = expandTemplate(template, {
    type: 'feature',
    color: '0e8a16'
  });
  
  expect(expanded).toEqual({
    name: 'task:feature',
    description: 'feature task',
    color: '0e8a16'
  });
});

test('should generate multiple labels from array values', () => {
  const template = {
    name: 'priority:${level}',
    color: '${color}'
  };
  
  const labels = generateFromTemplate(template, [
    { level: 'high', color: 'ff0000' },
    { level: 'medium', color: 'ffff00' },
    { level: 'low', color: '00ff00' }
  ]);
  
  expect(labels).toHaveLength(3);
  expect(labels[0].name).toBe('priority:high');
});
```

### 3. Built-in Templates
```javascript
test('should provide built-in templates', () => {
  const templates = getBuiltInTemplates();
  
  expect(templates).toHaveProperty('semantic-version');
  expect(templates).toHaveProperty('component-labels');
  expect(templates).toHaveProperty('workflow-states');
});

test('should generate semantic version labels', () => {
  const labels = generateFromBuiltIn('semantic-version');
  
  expect(labels).toContainEqual({
    name: 'release:major',
    description: 'Major version bump',
    color: expect.any(String)
  });
});
```

## Tasks
- [ ] Write template syntax tests
- [ ] Implement template parser
- [ ] Write variable extraction tests
- [ ] Implement variable extractor
- [ ] Write expansion tests
- [ ] Implement template expander
- [ ] Write built-in template tests
- [ ] Create template library
- [ ] Write validation tests
- [ ] Add template validation

## Template Examples
```yaml
# templates/component-labels.yaml
template:
  name: 'component:${name}'
  description: '${name} component related'
  color: '${color|0e8a16}'  # Default value

values:
  - name: frontend
    color: '7057ff'
  - name: backend
    color: '0e8a16'
  - name: database
    color: 'd73a4a'
```

```yaml
# templates/workflow.yaml
template:
  name: 'status:${state}'
  description: 'Issue is ${state}'
  color: '${colors[${state}]}'

colors:
  pending: 'fef2c0'
  in-progress: '7057ff'
  review: 'c5def5'
  done: '0e8a16'
```

## Built-in Templates
- **semantic-version**: major, minor, patch, breaking
- **component-labels**: frontend, backend, api, database
- **workflow-states**: backlog, todo, in-progress, review, done
- **issue-types**: bug, feature, docs, chore, refactor
- **priority-levels**: critical, high, medium, low

## Success Criteria
- Flexible template syntax
- Variable substitution
- Default values support
- Built-in useful templates
- Clear error messages

## Priority
🟡 **Medium Priority** - Enhances reusability
