### ISSUE TITLE
エージェント分離Phase 4: コンテナ化とオーケストレーション

### ISSUE THREAD

**Issue by medamap** [medamap/PoppoBuilderSuite#69]
## 概要
エージェントシステムをDockerコンテナ化し、Kubernetesによるオーケストレーションを実装します。これにより、本格的なマイクロサービスアーキテクチャへの移行を完了します。

## 背景
Phase 1-3でエージェント分離、メッセージキュー、動的スケーリングが実装されました。最終段階として、コンテナ化により環境の一貫性とポータビリティを確保し、Kubernetesによる高度な運用を実現します。

### 1. Dockerコンテナ化
各エージェント用のDockerfile作成：
```dockerfile
# agents/ccpm/Dockerfile
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY agents/ccpm ./agents/ccpm
COPY agents/shared ./agents/shared
CMD ["node", "agents/ccpm/index.js"]
```

### 2. Docker Composeによるローカル開発環境
```yaml
version: '3.8'
services:
  coordinator:
    build: ./agents/core
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    
  ccpm:
    build: ./agents/ccpm
    deploy:
      replicas: 2
    
  ccag:
    build: ./agents/ccag
    deploy:
      replicas: 2
    
  redis:
    image: redis:alpine
    
  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"
```

### 3. Kubernetes マニフェスト
```yaml
# k8s/deployments/ccpm-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccpm-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ccpm-agent
  template:
    metadata:
      labels:
        app: ccpm-agent
    spec:
      containers:
      - name: ccpm
        image: poppobuilder/ccpm:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
```

### 4. Horizontal Pod Autoscaler (HPA)
```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ccpm-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ccpm-agent
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
```

### 5. Helm Chartの作成
```
charts/poppobuilder/
├── Chart.yaml
├── values.yaml
├── templates/
│   ├── coordinator-deployment.yaml
│   ├── ccpm-deployment.yaml
│   ├── ccag-deployment.yaml
│   ├── ccla-deployment.yaml
│   ├── redis-deployment.yaml
│   ├── services.yaml
│   └── configmap.yaml
```

### 6. CI/CDパイプライン
```yaml
# .github/workflows/docker-build.yml
name: Docker Build and Push
on:
  push:
    branches: [main, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker images
      run: |
        docker build -t poppobuilder/coordinator:${{ github.sha }} ./agents/core
        docker build -t poppobuilder/ccpm:${{ github.sha }} ./agents/ccpm
        # ... 各エージェント用のビルド
```

## 実装ファイル

1. `Dockerfile` - 各エージェント用のDockerfile
2. `docker-compose.yml` - ローカル開発環境
3. `k8s/` - Kubernetesマニフェスト
4. `charts/poppobuilder/` - Helm Chart
5. `.github/workflows/docker-build.yml` - CI/CDパイプライン

### ローカル環境
```bash
docker-compose up -d
```

### Kubernetes環境
```bash
# Helm でデプロイ
helm install poppobuilder ./charts/poppobuilder

# または kubectl
kubectl apply -f k8s/
```

## 監視とロギング

- Prometheus/Grafanaによるメトリクス監視
- EFK (Elasticsearch, Fluentd, Kibana) スタックによるログ集約
- Jaegerによる分散トレーシング

## 期待される効果

- 環境の一貫性とポータビリティ
- Kubernetesによる高度な自動スケーリング
- ローリングアップデートによる無停止デプロイ
- リソースの効率的な利用
- 障害時の自動復旧

## セキュリティ考慮事項

- シークレット管理（Kubernetes Secrets）
- ネットワークポリシーによるエージェント間通信の制限
- 最小権限の原則に基づくRBAC設定
- コンテナイメージの脆弱性スキャン

## 前提条件

- Phase 3（動的スケーリング）が完了していること
- Docker環境が利用可能であること
- Kubernetes環境へのアクセス（本番デプロイ時）

#dogfooding
